// Generated by CoffeeScript 1.12.7
(function() {
  var _, normalizeName;

  _ = require('lodash');

  normalizeName = function(s) {
    var key, specialCharMapping, value;
    if (typeof s !== 'string') {
      return;
    }
    s = s.trim().toLowerCase();
    specialCharMapping = {
      "ä": "ae",
      "ö": "oe",
      "ü": "ue",
      "&": "and",
      "\\+": "plus",
      "ß": "ss",
      "@": "at"
    };
    for (key in specialCharMapping) {
      value = specialCharMapping[key];
      s = s.replace(new RegExp(key, 'g'), value);
    }
    return _.deburr(s.replace(/[\.,#¡!?¿@$%\^&\*;:{}='`‘’“”„"~()\?><\[\]†‡‹›•™¦©®ª«»¬°¹²³µ¶·º℅ⁿ§¨‣‼№♠♣♦♥←→↑↓♀♂♩♪♬♭]/g, '').replace(/\/|\_|\‾|\ |\\/g, '-').replace(/\-+/g, '-').replace(/^-|-$/g, ''));
  };

  module.exports = normalizeName;

}).call(this);
